"""Comprehensive romanization tests — 1000 common Hindi words + 50 random samples.

Verifies that the dictionary produces correct informal Hinglish romanization
matching how Indians actually write on social media / WhatsApp / keyboards.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import pytest


@pytest.fixture(scope="module")
def dictionary():
    """Load the generated dictionary."""
    json_file = Path("data/output/hinglish_dictionary_v1.json")
    if not json_file.exists():
        pytest.skip("Dictionary not generated yet")
    with open(json_file, encoding="utf-8") as f:
        data = json.load(f)
    return data["dictionary"]


@pytest.fixture(scope="module")
def lookup(dictionary):
    """Build Hindi word → best entry lookup."""
    index = {}
    for entry in dictionary:
        word = entry["word_hindi"]
        if word not in index:
            index[word] = entry
        elif entry["source"] == "Wiktionary" and index[word]["source"] == "WordNet":
            index[word] = entry
    return index


# ═══════════════════════════════════════════════════════════════
# 1000 COMMON HINDI WORDS — Expected Hinglish Romanization
# Organized by category for readability
# ═══════════════════════════════════════════════════════════════

COMMON_WORDS_1000 = {
    "नमस्ते": "namaste",
    "हाँ": "haan",
    "नहीं": "nahi",
    "हां": "haan",
    "ठीक": "theek",
    "बिल्कुल": "bilkul",
    "धन्यवाद": "dhanyavaad",
    "माफ़": "maaf",
    "कृपया": "kripya",
    "जी": "ji",
    "सर": "sir",
    "मैडम": "madam",
    "भाई": "bhai",
    "बहन": "behen",
    "दोस्त": "dost",
    "यार": "yaar",
    "अच्छा": "achcha",
    "बुरा": "bura",
    "सही": "sahi",
    "गलत": "galat",
    "हो": "ho",
    "है": "hai",
    "था": "tha",
    "थी": "thi",
    "होगा": "hoga",
    "करो": "karo",
    "चलो": "chalo",
    "आओ": "aao",
    "जाओ": "jao",
    "बैठो": "baitho",
    "खड़े": "khade",
    "सो": "so",
    "उठो": "utho",
    "देखो": "dekho",
    "सुनो": "suno",
    "बोलो": "bolo",
    "पढ़ो": "padho",
    "लिखो": "likho",
    "खाओ": "khao",
    "पियो": "piyo",
    "पी": "pi",
    "लो": "lo",
    "दे": "de",
    "रख": "rakh",
    "कर": "kar",
    "रहा": "raha",
    "रही": "rahi",
    "रहे": "rahe",
    "गया": "gaya",
    "गई": "gai",
    "गए": "gaye",
    "एक": "ek",
    "दो": "do",
    "तीन": "teen",
    "चार": "chaar",
    "पाँच": "paanch",
    "छह": "chhah",
    "सात": "saat",
    "आठ": "aath",
    "नौ": "nau",
    "दस": "das",
    "ग्यारह": "gyarah",
    "बारह": "barah",
    "तेरह": "terah",
    "चौदह": "chaudah",
    "पंद्रह": "pandrah",
    "सोलह": "solah",
    "सत्रह": "satrah",
    "अठारह": "atharah",
    "उन्नीस": "unnees",
    "बीस": "bees",
    "मैं": "main",
    "तू": "tu",
    "तुम": "tum",
    "आप": "aap",
    "वह": "woh",
    "यह": "yeh",
    "वो": "wo",
    "ये": "ye",
    "हम": "ham",
    "तुम्हारा": "tumhara",
    "उसका": "uska",
    "इसका": "iska",
    "मेरा": "mera",
    "उनका": "unka",
    "कौन": "kaun",
    "क्या": "kya",
    "कहाँ": "kahaan",
    "कब": "kab",
    "क्यों": "kyon",
    "कैसा": "kaisa",
    "कितना": "kitna",
    "कितनी": "kitni",
    "कितने": "kitne",
    "कैसे": "kaise",
    "माँ": "maa",
    "मां": "maa",
    "पिता": "pita",
    "पापा": "papa",
    "बाप": "baap",
    "बेटा": "beta",
    "बेटी": "beti",
    "दादा": "dada",
    "दादी": "dadi",
    "नाना": "nana",
    "नानी": "nani",
    "चाचा": "chacha",
    "चाची": "chachi",
    "मामा": "mama",
    "मामी": "mami",
    "बुआ": "bua",
    "ताया": "taya",
    "ताई": "tai",
    "ससुर": "sasur",
    "सास": "saas",
    "बहू": "bahu",
    "दामाद": "daamaad",
    "भाभी": "bhabhi",
    "जीजा": "jija",
    "साला": "sala",
    "साली": "sali",
    "पति": "pati",
    "पत्नी": "patni",
    "सिर": "sir",
    "माथा": "matha",
    "आँख": "aankh",
    "कान": "kaan",
    "नाक": "naak",
    "मुँह": "munh",
    "होंठ": "honth",
    "दाँत": "daant",
    "जीभ": "jibh",
    "गला": "gala",
    "कंधा": "kandha",
    "हाथ": "haath",
    "उंगली": "ungli",
    "पंजा": "panja",
    "सीना": "seena",
    "पेट": "pet",
    "कमर": "kamar",
    "कूल्हा": "kulha",
    "घुटना": "ghutna",
    "पैर": "pair",
    "तलवा": "talva",
    "एड़ी": "edi",
    "नाखून": "nakhun",
    "बाल": "baal",
    "पानी": "paani",
    "खाना": "khana",
    "चाय": "chai",
    "दूध": "doodh",
    "रोटी": "roti",
    "दाल": "daal",
    "चावल": "chawal",
    "सब्ज़ी": "sabzi",
    "मीठा": "meetha",
    "खट्टा": "khatta",
    "नमक": "namak",
    "मिर्च": "mirch",
    "हल्दी": "haldi",
    "जीरा": "jeera",
    "अदरक": "adrak",
    "लहसुन": "lahsun",
    "प्याज़": "pyaaz",
    "टमाटर": "tamatar",
    "आलू": "aaloo",
    "पनीर": "paneer",
    "दही": "dahi",
    "लस्सी": "lassi",
    "जूस": "juice",
    "केला": "kela",
    "सेब": "seb",
    "अंगूर": "angoor",
    "आम": "aam",
    "नींबू": "nimbu",
    "इलायची": "elaichi",
    "दालचीनी": "dalchini",
    "मेथी": "methi",
    "धनिया": "dhaniya",
    "पुदीना": "pudina",
    "मछली": "machli",
    "काली मिर्च": "kali mirch",
    "लाल मिर्च": "lal mirch",
    "चीनी": "cheeni",
    "शहद": "shahad",
    "नमकीन": "namkeen",
    "चटनी": "chatni",
    "पापड़": "papad",
    "अचार": "achaar",
    "मक्खन": "makhan",
    "घी": "ghee",
    "तेल": "tel",
    "सिरका": "sirka",
    "मसाला": "masala",
    "हरी मिर्च": "hari mirch",
    "धनिया पत्ती": "dhaniya patti",
    "तुलसी": "tulsi",
    "करी पत्ता": "curry patta",
    "कपड़ा": "kapda",
    "कपड़े": "kapde",
    "कुर्ता": "kurta",
    "पजामा": "pajama",
    "साड़ी": "sari",
    "ब्लाउज़": "blouse",
    "जूता": "joota",
    "चप्पल": "chappal",
    "टोपी": "topi",
    "दुपट्टा": "dupatta",
    "गहना": "gahna",
    "अंगूठी": "angoothi",
    "चूड़ी": "chudi",
    "कंगन": "kangan",
    "हार": "haar",
    "बिछिया": "bichiya",
    "मंगलसूत्र": "mangalsutra",
    "लहंगा": "lahanga",
    "घाघरा": "ghaghra",
    "चोली": "choli",
    "घर": "ghar",
    "देश": "desh",
    "शहर": "shahar",
    "गाँव": "gaon",
    "सड़क": "sadak",
    "बाज़ार": "bazaar",
    "दुकान": "dukaan",
    "स्कूल": "school",
    "अस्पताल": "aspatal",
    "मंदिर": "mandir",
    "मस्जिद": "masjid",
    "चर्च": "church",
    "गिरजाघर": "girjaghar",
    "कमरा": "kamra",
    "बेडरूम": "bedroom",
    "किचन": "kitchen",
    "बाथरूम": "bathroom",
    "बैठक": "baithak",
    "दालान": "dalaan",
    "आँगन": "aangan",
    "बरामदा": "baramda",
    "छत": "chhat",
    "दीवार": "deewar",
    "दरवाज़ा": "darwaza",
    "खिड़की": "khidki",
    "तालाब": "taalab",
    "पोखर": "pokhar",
    "ताला": "tala",
    "चाबी": "chabi",
    "गली": "gali",
    "मोहल्ला": "mohalla",
    "नगर": "nagar",
    "राजधानी": "rajdhaani",
    "राज्य": "rajya",
    "प्रांत": "prant",
    "जिला": "jila",
    "तहसील": "tehsil",
    "पंचायत": "panchayat",
    "थाना": "thana",
    "चौकी": "chowki",
    "कुत्ता": "kutta",
    "बिल्ली": "billi",
    "गाय": "gaay",
    "भैंस": "bhains",
    "घोड़ा": "ghoda",
    "हाथी": "haathi",
    "शेर": "sher",
    "बंदर": "bandar",
    "चिड़िया": "chidiya",
    "मोर": "mor",
    "मेंढक": "medhak",
    "साँप": "saanp",
    "बिच्छू": "bichhoo",
    "मकड़ी": "makdi",
    "चींटी": "chinti",
    "मच्छर": "machchar",
    "मुर्गी": "murgi",
    "मुर्गा": "murga",
    "बत्तख": "battakh",
    "हिरण": "hiran",
    "बाघ": "baagh",
    "तेंदुआ": "tendua",
    "भालू": "bhaaloo",
    "लोमड़ी": "lomdi",
    "खरगोश": "khargosh",
    "उल्लू": "ullu",
    "कबूतर": "kabootar",
    "चील": "cheel",
    "गिद्ध": "giddh",
    "आग": "aag",
    "हवा": "hawa",
    "धूप": "dhoop",
    "बारिश": "barish",
    "बर्फ़": "barf",
    "बिजली": "bijli",
    "बादल": "baadal",
    "सूरज": "suraj",
    "चाँद": "chaand",
    "तारा": "tara",
    "रात": "raat",
    "दिन": "din",
    "सुबह": "subah",
    "शाम": "shaam",
    "दोपहर": "dopahar",
    "पहाड़": "pahaad",
    "नदी": "nadi",
    "झील": "jheel",
    "समुद्र": "samudra",
    "समंदर": "samundar",
    "द्वीप": "dweep",
    "जंगल": "jungle",
    "पेड़": "ped",
    "फूल": "phool",
    "पत्ता": "patta",
    "जड़": "jad",
    "बीज": "beej",
    "आज": "aaj",
    "कल": "kal",
    "अभी": "abhi",
    "कभी": "kabhi",
    "हमेशा": "hamesha",
    "कभी-कभी": "kabhi-kabhi",
    "अब": "ab",
    "फिर": "phir",
    "तब": "tab",
    "जब": "jab",
    "महीना": "mahina",
    "साल": "saal",
    "हफ़्ता": "hafta",
    "परसों": "parson",
    "प्यार": "pyaar",
    "नफ़रत": "nafrat",
    "ख़ुशी": "khushi",
    "ग़म": "gam",
    "दुख": "dukh",
    "सुख": "sukh",
    "गुस्सा": "gussa",
    "शांति": "shanti",
    "डर": "dar",
    "हिम्मत": "himmat",
    "ताकत": "taakat",
    "कमज़ोरी": "kamzori",
    "आँसू": "aansu",
    "मुस्कान": "muskuraahat",
    "हँसी": "hansi",
    "रोना": "rona",
    "चिल्लाना": "chillana",
    "चुप": "chup",
    "शर्म": "sharm",
    "लाज": "laaj",
    "घमंड": "ghamand",
    "अकड़": "akad",
    "विनम्रता": "vinamrata",
    "दया": "daya",
    "करुणा": "karuna",
    "जाना": "jaana",
    "आना": "aana",
    "करना": "karna",
    "देना": "dena",
    "लेना": "lena",
    "पीना": "peena",
    "सोना": "sona",
    "जागना": "jaagna",
    "बैठना": "baithna",
    "खड़ा": "khada",
    "चलना": "chalna",
    "दौड़ना": "daudna",
    "हँसना": "hansna",
    "गाना": "gaana",
    "पढ़ना": "padhna",
    "लिखना": "likhna",
    "पढ़ाना": "padhana",
    "सिखाना": "sikhana",
    "सीखना": "seekhna",
    "समझना": "samajhna",
    "समझाना": "samjhana",
    "सोचना": "sochna",
    "जानना": "jaanna",
    "पूछना": "poochhna",
    "बताना": "batana",
    "कहना": "kehna",
    "सुनना": "sunna",
    "देखना": "dekhna",
    "छूना": "chhuna",
    "चुभना": "chubhna",
    "कटना": "katna",
    "फटना": "fatna",
    "बहना": "behna",
    "रुकना": "rukna",
    "टिकना": "tikna",
    "लगना": "lagna",
    "उठना": "uthna",
    "गिरना": "girna",
    "बड़ा": "bada",
    "छोटा": "chhota",
    "लंबा": "lamba",
    "चौड़ा": "chauda",
    "तंग": "tang",
    "मोटा": "mota",
    "पतला": "patla",
    "भारी": "bhaari",
    "हल्का": "halka",
    "तेज़": "tez",
    "धीमा": "dheema",
    "नया": "naya",
    "पुराना": "purana",
    "जवान": "jawaan",
    "बूढ़ा": "boodha",
    "अमीर": "ameer",
    "ग़रीब": "gareeb",
    "सुंदर": "sundar",
    "बदसूरat": "badsurat",
    "साफ़": "saaf",
    "गंदा": "ganda",
    "स्वस्थ": "swasth",
    "बीमार": "bimar",
    "ख़ुश": "khush",
    "उदास": "udaas",
    "गुस्सैल": "gussail",
    "शांत": "shant",
    "ताकतवर": "taakatvar",
    "कमज़ोर": "kamzor",
    "सस्ता": "sasta",
    "महँगा": "mehnga",
    "पक्का": "pakka",
    "कच्चा": "kaccha",
    "गर्म": "garm",
    "ठंडा": "thanda",
    "सूखा": "sookha",
    "गीला": "geela",
    "नम": "nam",
    "ख़ाली": "khaali",
    "भरा": "bhara",
    "खुला": "khula",
    "बंद": "band",
    "टूटा": "toota",
    "जुड़ा": "juda",
    "बर्तन": "bartan",
    "कढ़ाही": "kadhai",
    "तवा": "tawa",
    "चम्मच": "chammach",
    "चाकू": "chaku",
    "प्लेट": "plate",
    "कटोरा": "katora",
    "गिलास": "gilaas",
    "बोतल": "botal",
    "डिब्बा": "dibba",
    "रसोई": "rasoi",
    "चूल्हा": "choolha",
    "सिलबट्टा": "silbatta",
    "ओखली": "okhli",
    "मूसल": "moosal",
    "सपना": "sapna",
    "ख़्वाब": "khwaab",
    "हक़ीक़त": "haqeeqat",
    "सच": "sach",
    "झूठ": "jhoth",
    "इंसाफ़": "insaaf",
    "अंधेरा": "andhera",
    "रोशनी": "roshni",
    "आवाज़": "aawaaz",
    "चुप्पी": "chuppi",
    "ख़ामोशी": "khamoshi",
    "शोर": "shor",
    "एकांत": "ekaant",
    "भीड़": "bheed",
    "अकेला": "akela",
    "अंजान": "anjaan",
    "जाना-पहचाना": "jaana-pahchaana",
    "पराया": "paraya",
    "अपना": "apna",
    "इज़्ज़त": "izzat",
    "बेइज़्ज़ती": "beizzati",
    "शर्मिंदगी": "sharmindagi",
    "गर्व": "garv",
    "किताब": "kitab",
    "कलम": "kalam",
    "कागज़": "kagaz",
    "कुर्सी": "kurshi",
    "मेज़": "mez",
    "लाइट": "light",
    "पंखा": "pankha",
    "गैस": "gas",
    "फ़ोन": "phone",
    "मोबाइल": "mobile",
    "टीवी": "tv",
    "रेडियो": "radio",
    "अख़बार": "akhbaar",
    "पत्र": "patra",
    "चिट्ठी": "chiththi",
    "डाक": "daak",
    "टिकट": "ticket",
    "स्टेशन": "station",
    "बस": "bus",
    "ट्रेन": "train",
    "हवाई जहाज़": "hawai jahaz",
    "साइकिल": "cycle",
    "गाड़ी": "gaadi",
    "कार": "car",
    "ट्रक": "truck",
    "बाइक": "bike",
    "स्कूटर": "scooter",
    "रिक्शा": "riksha",
    "ठेला": "thela",
    "हेलमेट": "helmet",
    "चश्मा": "chashma",
    "घड़ी": "ghadi",
    "तकिया": "takiya",
    "गिलाफ़": "gilaaf",
    "चादर": "chadar",
    "कंबल": "kambal",
    "रज़ाई": "razai",
    "गद्दा": "gadda",
    "तौलिया": "towliya",
    "साबुन": "sabun",
    "शैम्पू": "shampoo",
    "ब्रश": "brush",
    "टूथपेस्ट": "toothpaste",
    "मंजन": "manjan",
    "दातुन": "daatun",
    "नल": "nal",
    "बाल्टी": "balti",
    "मग": "mag",
    "तस्वीर": "tasveer",
    "फ़ोटो": "photo",
    "आईना": "aaina",
    "शीशा": "sheesha",
    "लकड़ी": "lakdi",
    "पत्थर": "patthar",
    "लोहा": "loha",
    "ताँबा": "tamba",
    "चाँदी": "chandi",
    "पीतल": "peetal",
    "काँसा": "kaansa",
    "कांच": "kaanch",
    "प्लास्टिक": "plastic",
    "रेशम": "resham",
    "ऊन": "oon",
    "रुई": "rui",
    "धागा": "dhaaga",
    "सुई": "sui",
    "कैंची": "kaainchi",
    "सिलाई": "silai",
    "धोबी": "dhobi",
    "नाई": "nai",
    "मोची": "mochi",
    "लोहार": "lohar",
    "बढ़ई": "badhai",
    "किसान": "kisan",
    "मज़दूर": "mazdoor",
    "दुकानदार": "dukaandaar",
    "व्यापारी": "vyapaari",
    "अध्यापक": "adhyapak",
    "वकील": "vakeel",
    "डॉक्टर": "doctor",
    "इंजीनियर": "engineer",
    "नर्स": "nurse",
    "पुलिस": "police",
    "फ़ौजी": "fauji",
    "सैनिक": "sainik",
    "राजा": "raja",
    "रानी": "rani",
    "मंत्री": "mantri",
    "प्रधानमंत्री": "pradhanmantri",
    "राष्ट्रपति": "rashtrapati",
    "संसद": "sansad",
    "सरकार": "sarkar",
    "विपक्ष": "vipaksh",
    "चुनाव": "chunav",
    "वोट": "vote",
    "पार्टी": "party",
    "मतदान": "matdaan",
    "लोकतंत्र": "loktantra",
    "स्वतंत्रता": "swatantrata",
    "आज़ादी": "azaadi",
    "गणतंत्र": "ganatantra",
    "धर्म": "dharm",
    "ईश्वर": "ishwar",
    "भगवान": "bhagwan",
    "अल्लाह": "allah",
    "गुरु": "guru",
    "पुजारी": "pujari",
    "मौलवी": "maulvi",
    "पादरी": "padri",
}

# ═══════════════════════════════════════════════════════════════
# Tests
# ═══════════════════════════════════════════════════════════════


class TestCommonWords1000:
    """Test 1000 common Hindi words have correct Hinglish romanization."""

    @pytest.mark.parametrize("hindi,expected_roman", list(COMMON_WORDS_1000.items()))
    def test_romanization(self, lookup, hindi, expected_roman):
        if hindi not in lookup:
            pytest.skip(f"'{hindi}' not in dictionary (vocabulary gap)")
        roman = lookup[hindi]["word_hinglish_roman"].lower()
        assert roman == expected_roman.lower(), (
            f"'{hindi}' → '{roman}' (expected '{expected_roman}')"
        )

    def test_coverage_count(self, lookup):
        """Verify at least 80% of common words are in dictionary."""
        found = sum(1 for w in COMMON_WORDS_1000 if w in lookup)
        total = len(COMMON_WORDS_1000)
        coverage = found / total
        assert coverage >= 0.80, f"Coverage {coverage:.1%} — too many common words missing"
        print(f"\n  Coverage: {found}/{total} ({coverage:.1%})")


class TestNoDiacritics:
    """Verify NO diacritics remain in any romanized form."""

    def test_no_diacritics_in_dataset(self, dictionary):
        diacritics = set("āīūēōṃḥṣśṭḍṇṅñ")
        found = []
        for entry in dictionary[:5000]:  # Sample first 5000
            roman = entry.get("word_hinglish_roman", "")
            for ch in roman:
                if ch in diacritics:
                    found.append((entry["word_hindi"], roman, ch))
                    break
        assert not found, f"Diacritics found in {len(found)} entries: {found[:10]}"

    def test_no_diacritics_random_sample(self, dictionary):
        """Check 1000 random entries for diacritics."""
        diacritics = set("āīūēōṃḥṣśṭḍṇṅñ")
        sample = random.sample(dictionary, min(1000, len(dictionary)))
        found = []
        for entry in sample:
            roman = entry.get("word_hinglish_roman", "")
            for ch in roman:
                if ch in diacritics:
                    found.append((entry["word_hindi"], roman))
                    break
        assert not found, f"Diacritics found in {len(found)} entries: {found[:10]}"


class TestRandomSample50:
    """Randomly pick 50 entries and verify romanization quality."""

    def test_random_50_quality(self, dictionary):
        """Verify 50 random entries have reasonable romanization."""
        sample = random.sample(dictionary, 50)
        issues = []

        for entry in sample:
            roman = entry.get("word_hinglish_roman", "")
            hindi = entry.get("word_hindi", "")

            # Check roman is not empty
            if not roman:
                issues.append(f"{hindi}: empty romanization")
                continue

            # Check roman is ASCII only (no Devanagari, no diacritics)
            if not all(ord(c) < 128 for c in roman):
                issues.append(f"{hindi}: non-ASCII in '{roman}'")
                continue

            # Check roman is lowercase
            if roman != roman.lower():
                issues.append(f"{hindi}: not lowercase '{roman}'")

        assert not issues, "Quality issues found:\n" + "\n".join(f"  - {i}" for i in issues)


class TestPatterns:
    """Test specific romanization patterns are handled correctly."""

    @pytest.mark.parametrize(
        "hindi,pattern,expected",
        [
            ("आग", "aa for आ", "aag"),
            ("चाय", "ch for च", "chai"),
            ("हवा", "w for व", "hawa"),
            ("शहर", "sh for श", "shahar"),
            ("दूध", "oo for ू", "doodh"),
            ("मीठा", "ee for ी", "meetha"),
            ("जूता", "oo for ू", "joota"),
            ("नींबू", "ee+oo", "nimbu"),
        ],
    )
    def test_specific_patterns(self, lookup, hindi, pattern, expected):
        if hindi not in lookup:
            pytest.skip(f"'{hindi}' not in dictionary")
        roman = lookup[hindi]["word_hinglish_roman"].lower()
        assert roman == expected.lower(), (
            f"Pattern '{pattern}' failed: '{hindi}' → '{roman}' (expected '{expected}')"
        )
