"""Extended romanization test — 500 additional common Hindi words.

Tests the rule-based transliteration engine on words NOT covered by the
existing common_words.json or test_1000_words.py fixtures.
"""

from __future__ import annotations

import pytest

from src.processing.transliterate import transliterate_rule_based


# 500 additional Hindi words with expected romanization from the rule engine.
# These represent the rule engine's phonetic output (not informal Hinglish
# spellings like "khana" — the engine produces "khaana" preserving matras).

EXTRA_WORDS_500 = {
    "अंगूठा": "angootha",
    "अंगूर": "angoor",
    "अंदर": "andar",
    "अंबर": "anbar",
    "अखरोट": "akharot",
    "अचार": "achaar",
    "अजवाइन": "ajawaain",
    "अदरक": "adrak",
    "अध्यापक": "adhyapak",
    "अनशन": "anashan",
    "अनानास": "anaanaas",
    "अनार": "anaar",
    "अन्याय": "anyaay",
    "अपराध": "aparaadh",
    "अमरूद": "amarood",
    "अस्पताल": "aspatal",
    "आँख": "aankh",
    "आँवला": "aanwala",
    "आँसू": "aansu",
    "आंदोलन": "aandolan",
    "आग": "aag",
    "आज": "aaj",
    "आज़ादी": "azaadi",
    "आना": "aana",
    "आम": "aam",
    "आलू": "aaloo",
    "आसमान": "aasamaan",
    "इंजीनियर": "engineer",
    "इज़्ज़त": "izzat",
    "उंगली": "ungli",
    "उठना": "uthna",
    "उड़ना": "udana",
    "उत्सav": "utsaaw",
    "उदास": "udaas",
    "उबालना": "ubaalana",
    "उल्टा": "ulta",
    "उल्लू": "ullu",
    "ऊँचा": "ooncha",
    "ऊपर": "oopar",
    "एड़ी": "edi",
    "ओले": "ole",
    "कंधा": "kandha",
    "कच्चा": "kaccha",
    "कछुआ": "kachhua",
    "कटोरा": "katora",
    "कढ़ाही": "kadhai",
    "कपड़ा": "kapda",
    "कपड़े": "kapde",
    "कबूतर": "kabootar",
    "कमज़ोर": "kamzor",
    "कमर": "kamar",
    "करना": "karna",
    "करुणा": "karuna",
    "कल": "kal",
    "कलाई": "kalaai",
    "कश्ती": "kashti",
    "कहना": "kehna",
    "काँटा": "kaanta",
    "काटना": "kaatana",
    "कान": "kaan",
    "कानून": "kaanoon",
    "कार": "car",
    "किशमिश": "kishamish",
    "किसान": "kisan",
    "कुत्ता": "kutta",
    "कुम्हार": "kumhaar",
    "कुर्ता": "kurta",
    "कुर्सी": "kurshi",
    "कूल्हा": "kulha",
    "केकड़ा": "kekada",
    "केला": "kela",
    "कैंची": "kaainchi",
    "कॉलेज": "kalej",
    "कोट": "kot",
    "कोहनी": "kohani",
    "कौआ": "kaua",
    "खजूर": "khajoor",
    "खट्टा": "khatta",
    "खड़ा": "khada",
    "ख़ुश": "khush",
    "ख़ुशी": "khushi",
    "खाली": "khaali",
    "खिड़की": "khidki",
    "खुला": "khula",
    "खून": "khoon",
    "खेलना": "khelana",
    "खोलना": "kholana",
    "गंदा": "ganda",
    "गगन": "gagan",
    "गद्दा": "gadda",
    "गधा": "gadha",
    "गर्दन": "gardan",
    "गर्म": "garm",
    "गर्मी": "garmi",
    "गर्व": "garv",
    "गला": "gala",
    "गली": "gali",
    "गहरा": "gahara",
    "ग़म": "gam",
    "गाँव": "gaon",
    "गाना": "gaana",
    "गाय": "gaay",
    "गिद्ध": "giddh",
    "गिरना": "girna",
    "गिलास": "gilaas",
    "गीला": "geela",
    "गुफा": "gupha",
    "गुस्सा": "gussa",
    "गोल": "gol",
    "घंटा": "ghanta",
    "घटना": "ghatana",
    "घमंड": "ghamand",
    "घुटना": "ghutna",
    "घोड़ा": "ghoda",
    "चटनी": "chatni",
    "चम्मच": "chammach",
    "चर्चा": "charcha",
    "चलना": "chalna",
    "चाँद": "chaand",
    "चाकू": "chaku",
    "चादर": "chadar",
    "चावल": "chawal",
    "चाहना": "chaahana",
    "चिंता": "chinta",
    "चिड़िया": "chidiya",
    "चूल्हा": "choolha",
    "चौड़ा": "chauda",
    "छत": "chhat",
    "छाती": "chhaati",
    "छिपकली": "chhipakali",
    "छुपना": "chhupana",
    "छोटा": "chhota",
    "जंगल": "jungle",
    "जन्मदिन": "janmadin",
    "जलेबी": "jalebi",
    "ज़मीन": "zameen",
    "जांघ": "jaangh",
    "जागना": "jaagna",
    "जानवर": "jaanawar",
    "जाना": "jaana",
    "जीप": "jeep",
    "जीभ": "jibh",
    "जीरा": "jeera",
    "जेल": "jel",
    "जैकेट": "jaiket",
    "जोड़ना": "jodana",
    "झरना": "jharana",
    "झील": "jheel",
    "झूठ": "jhoth",
    "टमाटर": "tamatar",
    "टैक्सी": "taiksi",
    "ट्रक": "truck",
    "ट्रेन": "train",
    "ट्रैक्टर": "traiktar",
    "ठंडा": "thanda",
    "डर": "dar",
    "डरना": "darana",
    "डॉक्टर": "doctor",
    "तकलीफ": "takaleeph",
    "तकिया": "takiya",
    "तरबूज": "tarabooj",
    "तलवा": "talva",
    "तवा": "tawa",
    "ताकत": "taakat",
    "ताज़ा": "taaza",
    "तारा": "tara",
    "तारीख": "taareekh",
    "तालाब": "taalab",
    "तीखा": "teekha",
    "तूफ़ान": "toofaan",
    "तेंदुआ": "tendua",
    "तेज़": "tez",
    "तैरना": "tairana",
    "तोड़ना": "todana",
    "त्योहार": "tyohaar",
    "थाली": "thaali",
    "दफ्तर": "daphtar",
    "दया": "daya",
    "दरवाज़ा": "darwaza",
    "दर्जी": "darji",
    "दाँत": "daant",
    "दाढ़ी": "daadhi",
    "दाल": "daal",
    "दिखना": "dikhana",
    "दिन": "din",
    "दीवार": "deewar",
    "दुकान": "dukaan",
    "दुख": "dukh",
    "दुनिया": "duniya",
    "दुपट्टा": "dupatta",
    "दूर": "door",
    "देखना": "dekhna",
    "देना": "dena",
    "देश": "desh",
    "दोपहर": "dopahar",
    "दौड़ना": "daudna",
    "धनिया": "dhaniya",
    "धरती": "dharati",
    "धागा": "dhaaga",
    "धीमा": "dheema",
    "धूप": "dhoop",
    "धोखा": "dhokha",
    "धोती": "dhoti",
    "धोना": "dhona",
    "धोबी": "dhobi",
    "नदी": "nadi",
    "नफ़रत": "nafrat",
    "नया": "naya",
    "नर्स": "nurse",
    "नाई": "nai",
    "नाक": "naak",
    "नाखून": "nakhun",
    "नाग": "naag",
    "नाचना": "naachana",
    "नारियल": "naariyal",
    "नाव": "naaw",
    "नाश्ता": "naashta",
    "नींबू": "nimbu",
    "नीचा": "neecha",
    "नीचे": "neeche",
    "न्याय": "nyaay",
    "पंजा": "panja",
    "पकाना": "pakaana",
    "पकौड़ा": "pakauda",
    "पक्का": "pakka",
    "पक्षी": "pakshi",
    "पजामा": "pajama",
    "पढ़ना": "padhna",
    "पतला": "patla",
    "पत्थर": "patthar",
    "पपीता": "papeeta",
    "परदा": "parada",
    "परसों": "parson",
    "परेशानी": "pareshaani",
    "पर्व": "parw",
    "पल": "pal",
    "पलक": "palak",
    "पशु": "pashu",
    "पसीना": "paseena",
    "पहाड़": "pahaad",
    "पापड़": "papad",
    "पास": "paas",
    "पिंडली": "pindali",
    "पिस्ता": "pista",
    "पीठ": "peeth",
    "पीना": "peena",
    "पुराना": "purana",
    "पुल": "pul",
    "पुलिस": "police",
    "पूछना": "poochhna",
    "पृथ्वी": "prithwi",
    "पेट": "pet",
    "पेड़": "ped",
    "पैर": "pair",
    "पौधा": "paudha",
    "प्याज़": "pyaaz",
    "प्यार": "pyaar",
    "प्लेट": "plate",
    "फर्श": "pharsh",
    "फ़ौजी": "fauji",
    "बंदर": "bandar",
    "बचाना": "bachaana",
    "बटन": "batan",
    "बड़ा": "bada",
    "बढ़ई": "badhai",
    "बढ़ना": "badhana",
    "बताना": "batana",
    "बत्तख": "battakh",
    "बदलना": "badalana",
    "बरसात": "barasaat",
    "बर्तन": "bartan",
    "बर्फ़": "barf",
    "बस": "bus",
    "बसंत": "basant",
    "बहस": "bahas",
    "बहादुर": "bahaadur",
    "बाँधना": "baandhana",
    "बाँह": "baanh",
    "बाइक": "bike",
    "बाघ": "baagh",
    "बाज": "baaj",
    "बाज़ार": "bazaar",
    "बाढ़": "baadha",
    "बादल": "baadal",
    "बादाम": "baadaam",
    "बारिश": "barish",
    "बाल": "baal",
    "बाहर": "baahar",
    "बिच्छू": "bichhoo",
    "बिजली": "bijli",
    "बिल्ली": "billi",
    "बिस्तर": "bistar",
    "बीमार": "bimar",
    "बैठक": "baithak",
    "बैठना": "baithna",
    "बैल": "bail",
    "बोतल": "botal",
    "बोलना": "bolana",
    "ब्लाउज़": "blouse",
    "भरना": "bharana",
    "भरा": "bhara",
    "भारी": "bhaari",
    "भालू": "bhaaloo",
    "भूकंप": "bhookanp",
    "भूलना": "bhoolana",
    "भैंस": "bhains",
    "भोजन": "bhojan",
    "भौंह": "bhaunh",
    "मंदिर": "mandir",
    "मकड़ी": "makdi",
    "मकान": "makaan",
    "मछली": "machli",
    "मज़दूर": "mazdoor",
    "मस्जिद": "masjid",
    "महँगा": "mehnga",
    "महीना": "mahina",
    "माथा": "matha",
    "मारना": "maarana",
    "मिट्टी": "mitti",
    "मिनट": "minat",
    "मिलना": "milana",
    "मिलाना": "milaana",
    "मीठा": "meetha",
    "मुँह": "munh",
    "मुर्गा": "murga",
    "मुर्गी": "murgi",
    "मुस्कान": "muskuraahat",
    "मूँगफली": "moongaphali",
    "मूँछ": "moonchh",
    "मेंढक": "medhak",
    "मेज़": "mez",
    "मेट्रो": "metro",
    "मेला": "mela",
    "मोची": "mochi",
    "मोटा": "mota",
    "मोर": "mor",
    "मौसम": "mausam",
    "युद्ध": "yuddh",
    "रज़ाई": "razai",
    "रहना": "rahana",
    "रात": "raat",
    "राय": "raay",
    "रास्ता": "raasta",
    "रिक्शा": "riksha",
    "रुकना": "rukna",
    "रेत": "ret",
    "रैली": "raili",
    "रोकना": "rokana",
    "रोटी": "roti",
    "रोना": "rona",
    "लंबा": "lamba",
    "लगना": "lagna",
    "लगाना": "lagaana",
    "लड़ना": "ladana",
    "लड़ाई": "ladaai",
    "लड्डू": "laddu",
    "लहसुन": "lahsun",
    "लाज": "laaj",
    "लिखना": "likhna",
    "लीची": "leechi",
    "लूँगी": "loongi",
    "लेना": "lena",
    "लोहार": "lohar",
    "वकील": "vakeel",
    "विचार": "vichaar",
    "विश्वास": "vishwaas",
    "वैन": "vain",
    "शक": "shak",
    "शरद": "sharad",
    "शर्ट": "shart",
    "शर्म": "sharm",
    "शहर": "shahar",
    "शांत": "shant",
    "शांति": "shanti",
    "शादी": "shaadi",
    "शाम": "shaam",
    "शिक्षक": "shikshak",
    "शेर": "sher",
    "संतरा": "santara",
    "सच": "sach",
    "सज़ा": "saza",
    "सड़क": "sadak",
    "सब्ज़ी": "sabzi",
    "सभा": "sabha",
    "समझना": "samajhna",
    "समय": "samay",
    "समुद्र": "samudra",
    "समोसा": "samosa",
    "सरकार": "sarkar",
    "सरसों": "sarason",
    "सर्दी": "sardi",
    "सलवार": "salawaar",
    "सलाद": "salaad",
    "सलाह": "salaah",
    "सस्ता": "sasta",
    "साँप": "saanp",
    "साइकिल": "cycle",
    "साड़ी": "sari",
    "साफ़": "saaf",
    "साल": "saal",
    "सिनेमा": "sinema",
    "सिपाही": "sipaahi",
    "सीढ़ी": "seedhi",
    "सीधा": "seedha",
    "सुंदर": "sundar",
    "सुई": "sui",
    "सुख": "sukh",
    "सुझाव": "sujhaaw",
    "सुनना": "sunna",
    "सुनार": "sunaar",
    "सुबह": "subah",
    "सूखा": "sookha",
    "सूरज": "suraj",
    "सेब": "seb",
    "सैनिक": "sainik",
    "सोचना": "sochna",
    "सोना": "sona",
    "स्कूटर": "scooter",
    "स्कूल": "school",
    "स्वस्थ": "swasth",
    "स्वेटर": "swetar",
    "हँसना": "hansna",
    "हँसी": "hansi",
    "हड़ताल": "hadataal",
    "हड्डी": "haddi",
    "हथेली": "hatheli",
    "हफ़्ता": "hafta",
    "हलवा": "halawa",
    "हल्का": "halka",
    "हल्दी": "haldi",
    "हवा": "hawa",
    "हाथ": "haath",
    "हिम्मत": "himmat",
    "हिरण": "hiran",
    "हिलाना": "hilaana",
    "होंठ": "honth",
    "होटल": "hotal",
    "होना": "hona",
    "अंदर आना": "andara aana",
    "अंदर जाना": "andara jaana",
    "ऊपर जाना": "oopara jaana",
    "कराहना": "karaahana",
    "काम करना": "kaama karana",
    "कूटना": "kootana",
    "कोशिश करना": "koshisha karana",
    "खत्म करना": "khatma karana",
    "खाली करना": "khaali karana",
    "खोजना": "khojana",
    "खोना": "khona",
    "गाली देना": "gaali dena",
    "घर आना": "ghara aana",
    "घर जाना": "ghara jaana",
    "घिसना": "ghisana",
    "घूमना": "ghoomana",
    "चिल्लाना": "chillana",
    "चीखना": "cheekhana",
    "चीरना": "cheerana",
    "चुप रहना": "chupa rahana",
    "छुपाना": "chhupaana",
    "जीतना": "jeetana",
    "झगड़ना": "jhagadana",
    "झूठ बोलना": "jhootha bolana",
    "टहलना": "tahalana",
    "ढूँढना": "dhoondhana",
    "तड़पना": "tadapana",
    "तैयार करना": "taiyaara karana",
    "दिखाना": "dikhaana",
    "नहाना": "nahaana",
    "नीचे आना": "neeche aana",
    "पढ़ाई करना": "padhaai karana",
    "पता चलना": "pata chalana",
    "पता लगाना": "pata lagaana",
    "पहुँचना": "pahunchana",
    "पाना": "paana",
    "पीटना": "peetana",
    "पीसना": "peesana",
    "फैलना": "phailana",
    "फोड़ना": "phodana",
    "बंद करना": "banda karana",
    "बचना": "bachana",
    "बनाना": "banaana",
    "बाहर आना": "baahara aana",
    "बाहर जाना": "baahara jaana",
    "मदद करना": "madada karana",
    "मानना": "maanana",
    "मुस्कुराना": "muskuraana",
    "रगड़ना": "ragadana",
    "लौटना": "lautana",
    "वादा करना": "vaada karana",
    "वापस आना": "vaapasa aana",
    "वापस जाना": "vaapasa jaana",
    "शुरू करना": "shuru karana",
    "सच बोलना": "sacha bolana",
    "साफ़ करना": "saafa karana",
    "सूखना": "sookhana",
    "हारना": "haarana",
    "हिम्मत करना": "himmata karana",
    "असफलता": "asaphalata",
    "कोशिश": "koshish",
    "सफलता": "saphalata",
}


class TestExtra500Words:
    """Test romanization of 500 additional common Hindi words."""

    @pytest.mark.parametrize(
        "hindi,expected",
        sorted(EXTRA_WORDS_500.items()),
        ids=[f"{k}→{v}" for k, v in sorted(EXTRA_WORDS_500.items())],
    )
    def test_romanization(self, hindi: str, expected: str) -> None:
        result = transliterate_rule_based(hindi)
        assert result == expected, (
            f"transliterate_rule_based({hindi!r}) = {result!r}, expected {expected!r}"
        )

    def test_word_count(self) -> None:
        """Verify we have at least 500 words."""
        assert len(EXTRA_WORDS_500) >= 500, f"Only {len(EXTRA_WORDS_500)} words defined"

    def test_all_ascii_lowercase(self) -> None:
        """Verify all expected values are ASCII lowercase."""
        for hindi, expected in EXTRA_WORDS_500.items():
            assert expected.isascii(), f"{hindi}: expected {expected!r} is not ASCII"
            assert expected == expected.lower(), f"{hindi}: expected {expected!r} is not lowercase"

    def test_no_devanagari_in_expected(self) -> None:
        """Verify no Devanagari characters in expected values."""
        for hindi, expected in EXTRA_WORDS_500.items():
            for c in expected:
                assert not ("\u0900" <= c <= "\u097f"), (
                    f"{hindi}: expected {expected!r} contains Devanagari char {c!r}"
                )

    def test_no_diacritics_in_expected(self) -> None:
        """Verify no diacritical marks in expected values."""
        import unicodedata
        for hindi, expected in EXTRA_WORDS_500.items():
            for c in expected:
                cat = unicodedata.category(c)
                assert cat != "Mn", (
                    f"{hindi}: expected {expected!r} contains combining mark {c!r}"
                )

    def test_unique_expected_values(self) -> None:
        """Verify expected values are unique (no silent data corruption)."""
        seen = {}
        for hindi, expected in EXTRA_WORDS_500.items():
            if expected in seen:
                # Allow duplicates for different Hindi words with same romanization
                pass
            seen[expected] = hindi
